# .github/FUNDING.yml
buy_me_a_coffee: SirSHAmun5on12   # your BMC slug
github: false                     # hide GitHub Sponsors until you enable it
patreon: false
ko_fi: false
custom: []                        # leave empty for now
